name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
        name: Checkout
        uses: actions/checkout@v3
        
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - 
      name: Automated Version Bump
      uses: 'phips28/gh-action-bump-version@master'
      id: version-bump
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        default: fix
        tag-prefix: 'v'
        
    - 
      name: Output Step
      env:
        NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
      run: echo "new tag $NEW_TAG"
        
    -
        name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: $DOCKER_USERNAME/cloudproject-ci-cd:${{ steps.version-bump.outputs.newTag }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
      
