name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  username: ${{ secrets.DOCKER_USERNAME }}
  password: ${{ secrets.DOCKER_PASSWORD }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.username }}
        password: ${{ env.password }}
        
    -
      name: Build and push the Docker image
      run: 
        docker build . --file Dockerfile --tag "$username/cloudproject-ci-cd:${{github.head_ref}}"
        docker run "$username/cloudproject-ci-cd:${{github.head_ref}}"
        docker push "$username/cloudproject-ci-cd:${{github.head_ref}}"
